use axum::http::StatusCode;

pub trait Problem {
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    fn status(&self) -> StatusCode;

    /// A short, human-readable summary of the problem type.
    fn title(&self) -> &'static str;

    /// A human-readable explanation specific to this occurrence of the problem.
    fn detail(&self) -> String;

    /// A URI reference that identifies the problem type.
    /// Defaults to "about:blank" per the RFC.
    fn r#type(&self) -> &'static str {
        "about:blank"
    }

    /// A URI reference that identifies the specific occurrence of the problem.
    fn instance(&self) -> Option<String> {
        None
    }

    /// Additional arbitrary JSON data to merge into the top level of the response.
    fn extensions(&self) -> Option<serde_json::Map<String, serde_json::Value>> {
        None
    }
}

impl Problem for std::convert::Infallible {
    fn status(&self) -> StatusCode {
        match *self {}
    }
    fn title(&self) -> &'static str {
        match *self {}
    }
    fn detail(&self) -> String {
        match *self {}
    }
}

pub use bloodlegion_macros::Problem;

#[derive(serde::Serialize)]
struct SerializableProblem<'a> {
    status: u16,
    title: &'a str,
    detail: String,
    r#type: &'a str,

    #[serde(skip_serializing_if = "Option::is_none")]
    instance: Option<String>,

    #[serde(flatten)]
    extensions: Option<serde_json::Map<String, serde_json::Value>>,
}

pub trait IntoProblemResponse {
    fn into_problem_response(self) -> axum::response::Response;
}

impl<T: Problem> IntoProblemResponse for T {
    fn into_problem_response(self) -> axum::response::Response {
        axum::response::IntoResponse::into_response((
            self.status(),
            [(axum::http::header::CONTENT_TYPE, "application/problem+json")],
            axum::Json(SerializableProblem {
                status: self.status().as_u16(),
                title: self.title(),
                detail: self.detail(),
                r#type: self.r#type(),
                instance: self.instance(),
                extensions: self.extensions(),
            }),
        ))
    }
}
