version = 1

[[annotations]]
path = [
    "apps/web/**",
    "crates/*/**",
    ".cargo/config.toml",
    ".containerignore",
    ".github/**",
    ".gitattributes",
    ".gitignore",
    "Caddyfile",
    "Cargo.lock",
    "Cargo.toml",
    "README.md",
]
SPDX-FileCopyrightText = "2026 Jonathan Eyolfson <jon@eyolfson.com>"
SPDX-License-Identifier = "MIT OR Apache-2.0"
